_partial_: true
_target_: legged_gym.env.isaacgym.constraints.LinkPosePair
violation_weight: 0.0
penalty_weight: -1.0
terminate_on_violation: false
target_distance: 0.0
target_angle: 0.0
position_weight: 1.0
orientation_weight: 0.0
link_1: ???
link_2: ???
distance_sigma: 0.5
angle_sigma: 0.1
planar: false
mode: exact