_partial_: true
_target_: legged_gym.env.isaacgym.constraints.PointBodyAtGripper
violation_weight: 0.0
penalty_weight: -1.0
terminate_on_violation: false
power: 2.0
gripper_link_name: ???
dimensions:
  - 1