defaults:
  - env_aliengoLerobot
  - tasks@tasks.locomotion: local_2d_vel
  - constraints@constraints.action_rate: action_rate
  - constraints@constraints.joint_acc: joint_acc
  - constraints@constraints.collision: collision
  # - constraints@constraints.feet_drag: feet_drag
  - constraints@constraints.joint_limit: joint_limit
  - constraints@constraints.torque: torque
  # - constraints@constraints.energy: energy
  # - constraints@constraints.foot_contact_force: foot_contact_force
  - _self_

headless: True
ctrl_delay:
  data:
  # quadruped
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
   - 0.020
controller:
  _target_: legged_gym.env.isaacgym.control.PositionControllerWithExtraFixedAction
  extra_action:
    _target_: torch.full
    size:
      - 6
    fill_value: 0.0
    device: ${...sim_device}
  control_dim: 18
  offset:
    data:
      # Front Right
      - 0.1 # hip
      - 0.8 # thigh
      - -1.5 # calf
      # Front Left
      - -0.1 # hip
      - 0.8 # thigh
      - -1.5 # calf
      # Back Right
      - 0.1 # hip
      - 1.0 # thigh
      - -1.5 # calf
      # Back Left
      - -0.1 # hip
      - 1.0 # thigh
      - -1.5 # calf
      # Arm
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
  kp:
    _target_: torch.tensor
    data:
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
      - 50.0
        #
      - 100.0
      - 400.0
      - 100.0
      - 20.0
      - 20.0
      - 5.0
  kd:
    _target_: torch.tensor
    data:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
        # 
      - 1.0
      - 1.0
      - 1.0
      - 0.5
      - 0.5
      - 0.5
state_obs:
  dof_pos:
    dim: 18
  dof_vel:
    dim: 18
privileged_state_obs:
  dof_pos:
    dim: 18
  dof_vel:
    dim: 18
cfg:
  init_state:
    pos:  
      - -0.5
      - 0.0
      - 0.35
  env:
    num_observations: 57
    num_privileged_obs: 136   # change from 104 to 136
    num_actions: 12
    num_envs: 4096
  asset:
    name: aliengoPiper_fixedarm
    terminate_after_contacts_on:
      - base
      - hip
      - thigh
  rewards:
    scales:
      # not used
      orientation: 0.0
      # used
      lin_vel_z: -2.0
      ang_vel_xy: -0.05
tasks:
  local_2d_vel:
    tracking_sigma: 25
  locomotion:
    feet_sensor_indices:
      - 0
      - 1
      - 2
      - 3
constraints:
  collision:
    penalty_weight: -2.0
  action_rate:
    penalty_weight: -0.05
    joint_names:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      #
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      #
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      #
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
  feet_drag:
    penalty_weight: -0.01
  energy:
    penalty_weight: -1e-6
  joint_limit:
    joint_names:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      #
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      #
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      #
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
    lower:
      data:
        # Front Right
        - -1.2217304763960306 # hip
        - -0.524 # thigh
        - -2.775073510670984 # calf
        # Front Left
        - -1.2217304763960306 # hip
        - -0.524 # thigh
        - -2.775073510670984 # calf
        # Back Right
        - -1.2217304763960306 # hip
        - -0.524 # thigh
        - -2.775073510670984 # calf
        # Back Left
        - -1.2217304763960306 # hip
        - -0.524 # thigh
        - -2.775073510670984 # calf
    upper:
      data:
        # Front Right
        - 1.2217304763960306 # hip
        - 3.927 # thigh
        - -0.6457718232379019 # calf
        # Front Left
        - 1.2217304763960306 # hip
        - 3.927 # thigh
        - -0.6457718232379019 # calf
        # Back Right
        - 1.2217304763960306 # hip
        - 3.927 # thigh
        - -0.6457718232379019 # calf
        # Back Left
        - 1.2217304763960306 # hip
        - 3.927 # thigh
        - -0.6457718232379019 # calf
