0:
  _target_: torch.tensor
  data:
    - - -0.1
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.1
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
100000:
  _target_: torch.tensor
  data:
    - - -0.2
      - 0.0
      - 0.0
      - -0.2
      - -0.2
      - -0.2
    - - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
200000:
  _target_: torch.tensor
  data:
    - - -0.4
      - 0.0
      - 0.0
      - -0.4
      - -0.4
      - -0.4
    - - 0.4
      - 0.5
      - 0.5
      - 0.4
      - 0.4
      - 0.4
400000:
  _target_: torch.tensor
  data:
    - - -0.8
      - 0.0
      - 0.0
      - -0.8
      - -0.8
      - -0.8
    - - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
800000:
  _target_: torch.tensor
  data:
    - - -1.6
      - 0.0
      - 0.0
      - -1.6
      - -1.6
      - -1.6
    - - 1.6
      - 1.6
      - 1.6
      - 1.6
      - 1.6
      - 1.6
1000000:
  _target_: torch.tensor
  data:
    - - -2.0
      - 0.0
      - 0.0
      - -2.0
      - -2.0
      - -2.0
    - - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
1200000:
  _target_: torch.tensor
  data:
    - - -4.0
      - 0.0
      - 0.0
      - -4.0
      - -4.0
      - -4.0
    - - 4.0
      - 4.0
      - 4.0
      - 4.0
      - 4.0
      - 4.0
1400000:
  _target_: torch.tensor
  data:
    - - -4.0
      - 0.0
      - 0.0
      - -6.0
      - -6.0
      - -6.0
    - - 4.0
      - 8.0
      - 8.0
      - 6.0
      - 6.0
      - 6.0
1600000:
  _target_: torch.tensor
  data:
    - - -4.0
      - 0.0
      - 0.0
      - -6.0
      - -6.0
      - -6.0
    - - 4.0
      - 12.0
      - 12.0
      - 6.0
      - 6.0
      - 6.0